apiVersion: operator.curve.io/v1
kind: Curvefs
metadata:
  name: my-fscluster
  namespace: curve
spec:
  # The container image used to launch the Curve daemon pods(etcd, mds, metaserver).
  # v1.2 is Pacific and v1.3 is not tested.
  curveVersion:
    image: curve2operator/curvefs:monitor-v2.4.0-beta2
  # The K8s cluster nodes name in cluster that prepare to deploy Curve daemon pods(etcd, mds, metaserver).
  # For stand-alone deployment, set one host here and see fscluster-onehost.yaml
  # - node1 -> etcd-a, mds-a, metaserver-a
  # - node2 -> etcd-b, mds-b, metaserver-b
  # - node3 -> etcd-c, mds-c, metaserver-c
  nodes:
  - curve-worker
  - curve-worker2
  - curve-worker3
  # DataDirHostPath and LogDirHostPath where data files and log files will be persisted on host machine. Must be specified.
  # If you reinstall the cluster, make surce that you delete this directory from each host.
  dataDir: /curvefs
  logDir: /curvefs
  copySets: 100
  etcd:
    # Port for listening to partner communication. 
    # Etcd member accept incoming requests from its peers on a specific scheme://IP:port combination and the IP is host ip because we use hostnetwork:true.
    peerPort: 23800
    # clientPort for listening server port.
    clientPort: 23790
  mds:
    port: 6700
    dummyPort: 7700
  metaserver:
    port: 16800
    externalPort: 16800